apiVersion: v1
kind: Secret
metadata:
  name: {{ include "poligono.fullname" . }}
  labels:
    {{- include "poligono.labels" . | nindent 4 }}
type: Opaque
data:
  GEMINI_API_KEY: '{{ .Values.secrets.geminiApiKey | b64enc }}'
  MONGODB_URI: '{{ .Values.secrets.mongoURI | b64enc }}'
  INFISICAL_CLIENT_ID: '{{ .Values.secrets.infisicalClientId | b64enc }}'
  INFISICAL_CLIENT_SECRET: '{{ .Values.secrets.infisicalClientSecret | b64enc }}'
  INFISICAL_PROJECT_ID: '{{ .Values.secrets.infisicalProjectId | b64enc }}'
  QUERY_ENGINE_DSN: '{{ .Values.secrets.queryEngineDSN | b64enc }}'
  OAUTH2_ISSUER: '{{ .Values.secrets.oauth2Issuer | b64enc }}'
  OAUTH2_AUDIENCE: '{{ .Values.secrets.oauth2Audience | b64enc }}'